### ISSUE TITLE
Bug issued by HA

### ISSUE THREAD

**Issue by Lantoit** [basbruss/adaptive-cover#193] opened 2024-06-02 17:22 UTC
### What version of Adaptive Cover are you using?

1.2.1

### What version of Home Assistant are you using?

1.2.1

### Checklist

- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

From HA log:

Detected blocking call to import_module inside the event loop by custom integration 'adaptive_cover' at custom_components/adaptive_cover/sun.py, line 26: times = pd.date_range( (offender: /usr/local/lib/python3.12/site-packages/pandas/compat/_optional.py, line 132: module = importlib.import_module(name)), please create a bug report at https://github.com/basbruss/adaptive-cover/issues

### Reproduction steps

1.
Rebooting HA
2.
See the log
3.
...

**Comment by basbruss** [comment] 2024-06-02 17:35
duplicate of #134

**Closed as not planned by basbruss** 2024-06-02 17:35 UTC
Labels: duplicate
