### ISSUE TITLE
Automation switch is turned on when HA restarts -> Update: Blinds are tilted when HA restarts

### ISSUE THREAD

**Issue by x4N70pHyLL** [basbruss/adaptive-cover#115] opened 2024-04-18 13:53 UTC
## System Information

version | core-2024.4.3
-- | --
installation_type | Home Assistant Container
dev | false
hassio | false
docker | true
user | root
virtualenv | false
python_version | 3.12.2
os_name | Linux
os_version | 4.4.302+
arch | x86_64
timezone | Europe/Berlin
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.34.0
Stage | running
Available Repositories | 1469
Downloaded Repositories | 12

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Dashboards</summary>

dashboards | 3
-- | --
resources | 3
views | 11
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 8. April 2024 um 05:21
-- | --
current_recorder_run | 18. April 2024 um 07:49
estimated_db_size | 507.46 MiB
database_engine | sqlite
database_version | 3.44.2

</details>

### Checklist

- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

I have the issue that on a restart of HA all automation switches of the blinds are turned on. So even if I turn them off manually or via automation (winter, no sun, etc), on a HA restart they are always turned back on.

That has for example the effect that my tilted blinds are moving a bit even when in opened position and thus doors can not be opened or blinds are potentially damaged by the doors (user does not notice if blind is only 2% closed, but door will bump against the blind once opened).

### Reproduction steps

1. set up cover automation (without climate mode - just basic)
2. turn off switch that controls automation
3. restart Home Assistant
4. Switch is turned back on

EDIT: With updating to 1.1.0, the switches remain off an HA restart, but the covers will tilt on a restart to the latest calculated position from the automation sensor.

**Comment by basbruss** [comment] 2024-04-18 14:04
@x4N70pHyLL What version of the integration are you running?

**Comment by x4N70pHyLL** [comment] 2024-04-18 14:16
> @x4N70pHyLL What version of the integration are you running?

Up until today I used the 1.0.1 where the issue occurred.

I just retested with 1.1.0 indeed the switches seem to stay "off", but the blinds are moved in the calculated target position from the integration when restarting HA.

So sorry for not using the latest version, the issue seems now different, will change in the description

**Comment by basbruss** [comment] 2024-04-18 14:20
Then this is a sort of duplicate of #110.

**Comment by x4N70pHyLL** [comment] 2024-04-19 06:11
I think "sort of" only. I also noticed the behavior from #110 , however that is only when I change configuration, which I can kind of oversee and control. What is much more difficult to control is the behavior on start/restart of Home Assistant, if you need to take care manually after each restart, otherwise you blinds begin to move

If you think it is a duplicate or at least a result from the same base issue:
Should I close it or did you link it with the other in a way that it will be closed once the other is fixed?

**Closed as completed** 2024-04-22 15:48 UTC
Labels: bug
