### ISSUE TITLE
Add a end time after which covers should not be triggered automatically 

### ISSUE THREAD

**Issue by bend** [basbruss/adaptive-cover#151] opened 2024-05-14 20:09 UTC
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

I'm always frustrated when I close my blinds during the night as a protection for mosquitoes and the blind gets opened automatically 

### Describe the solution you'd like

I'd like to have the same as start date but for the end of the automation 

### Describe alternatives you've considered

I have to disable manually the adaptive cover 

### Additional context

No other context

**Comment by basbruss** [comment] 2024-05-14 20:35
duplicate of #135

**Comment by bend** [comment] 2024-05-14 20:52
@basbruss not the same request. #135 is requesting a feature to close covers after a specific time.
My request is to stop triggering the covers after a fixed time.

For example we use our sunshields as mosquito protection in the evening but at night we reopen the covers. With #135 it will keep closing them

**Closed as completed** 2024-05-16 12:20 UTC
Labels: 🚀 feature-request
